# Generated by Django 5.1.3 on 2025-05-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff')], max_length=20),
        ),
    ]
